# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3510eae2effe45e7b0c0c90403d371d9622ddaeafc21ddaf15ee3954c2d931fecbcacee274337489802a5e9674b92774d60d057dc7c362105fd0b9e76d28937e

test:
  secret_key_base: 25d376eed918248f7ed5e8484f425c873d8c28c0259839df518850c308a9294dcc6c47c1fe9eb0c8dc64dd563e348d7d8cc61f6ea25492f65af3131f8b676cb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
