# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88a0c366d9cfbd77593d1843018aff2a6c12f8d26501b5984b398882d0dfa655a13ed0cd13bc2ca2ad4c83b55cd23683177203480500b0ccb622df920a667d91

test:
  secret_key_base: 0f651cf80e3a64acc492b17c8d7647d620cd4d5eb8f92893822792b58f0f5bfc387e3d8763a3d53f0c8ef09865d85d239390390abd4ae4bc204fb4fd77723b93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
