# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce9154a10e767c3661d71028f260baeb66d93bb20b9973cc9d5c057328324a738467b7e58dba96dab3f780b6f5ef22c5628164747220d66b0e0bfddb0e554432

test:
  secret_key_base: 1785e9580b3b3c596617d9f92729aa9c7937db4e4c79ef1b6f7ce480cfdc8995dbfb648e399b4a84387fc172b4f2a9aa96c777257dea1755e892ed5d09fa8344

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
